@MyWebApp_HostAddress = http://localhost:5173

### Get a sample Lookup
GET {{MyWebApp_HostAddress}}/lookup
Accept: application/json

###

### Post new Lookup
POST {{MyWebApp_HostAddress}}/lookup
Content-Type: application/json

{
  "id": "00000000-0000-0000-0000-000000000001",
  "continuumOrderIdentifier": "CONT-ABC123",
  "merchantOrderIdentifier": "MER-123",
  "merchantId": 101,
  "saleCurrencyId": 978,
  "saleValue": 123.45,
  "resultCodeId": 0,
  "creationTimestamp": "2025-04-18T12:00:00Z",
  "versionSequence": 1,
  "orderSessionId": "SESSION-999"
}